# Generated by Django 4.2.3 on 2023-07-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0002_alter_orders_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="amountpaid",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="oid",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="paymentstatus",
        ),
    ]
