# Generated by Django 4.2.3 on 2023-07-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0003_remove_orders_amountpaid_remove_orders_oid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="razorpay_payment_id",
        ),
        migrations.AddField(
            model_name="orderupdate",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderupdate",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
