# Generated by Django 4.2.3 on 2023-07-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerceapp",
            "0004_remove_orders_paid_remove_orders_razorpay_payment_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orderupdate",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
